const router=require('express').Router();
const {pool}=require('../db');
const autorizado=u=>u&&['admin','bibliotecologa'].includes(u.rol);
const exigir=(req,res,next)=>autorizado(req.session.usuario)?next():res.status(403).json({error:'Sin permisos para Biblioteca'});
router.use(exigir);

router.get('/items',async(req,res)=>{const r=await pool.query(`SELECT i.*,i.stock_total-COALESCE((SELECT SUM(p.cantidad) FROM biblioteca_prestamos p WHERE p.item_id=i.id AND p.estado='prestado'),0)::int AS disponibles FROM biblioteca_items i WHERE i.activo IS TRUE ORDER BY i.categoria,i.nombre`);res.json(r.rows);});
router.post('/items',async(req,res)=>{const {codigo,nombre,categoria,stock_total}=req.body;if(!nombre?.trim()||!categoria?.trim())return res.status(400).json({error:'Nombre y categoría son requeridos.'});const r=await pool.query(`INSERT INTO biblioteca_items(codigo,nombre,categoria,stock_total,creado_por) VALUES(NULLIF($1,''),$2,$3,$4,$5) RETURNING *`,[(codigo||'').trim(),nombre.trim(),categoria.trim(),Math.max(0,Number(stock_total)||0),req.session.usuario.id]);res.json(r.rows[0]);});
router.put('/items/:id',async(req,res)=>{const {codigo,nombre,categoria,stock_total,activo}=req.body;const r=await pool.query(`UPDATE biblioteca_items SET codigo=NULLIF($1,''),nombre=$2,categoria=$3,stock_total=$4,activo=$5 WHERE id=$6 RETURNING *`,[(codigo||'').trim(),nombre?.trim(),categoria?.trim(),Math.max(0,Number(stock_total)||0),activo!==false,req.params.id]);if(!r.rows.length)return res.status(404).json({error:'Artículo no encontrado'});res.json(r.rows[0]);});
router.get('/secciones',async(req,res)=>{const r=await pool.query('SELECT id,nombre,nivel FROM secciones WHERE activa IS NOT FALSE ORDER BY nivel,nombre');res.json(r.rows);});
router.get('/estudiantes/:seccionId',async(req,res)=>{const r=await pool.query(`SELECT id,cedula,nombre,primer_apellido,segundo_apellido,subgrupo FROM estudiantes WHERE seccion_id=$1 AND activo=true AND COALESCE(archivado,false)=false ORDER BY primer_apellido,segundo_apellido,nombre`,[req.params.seccionId]);res.json(r.rows);});
router.get('/prestamos',async(req,res)=>{const estado=req.query.estado||'prestado';const r=await pool.query(`SELECT p.*,i.nombre AS item_nombre,i.codigo,e.cedula,e.nombre,e.primer_apellido,e.segundo_apellido,s.nombre AS seccion_nombre,u.nombre AS creador_nombre,u.primer_apellido AS creador_ap1 FROM biblioteca_prestamos p JOIN biblioteca_items i ON i.id=p.item_id JOIN estudiantes e ON e.id=p.estudiante_id LEFT JOIN secciones s ON s.id=e.seccion_id LEFT JOIN usuarios u ON u.id=p.creado_por WHERE ($1='todos' OR p.estado=$1) ORDER BY CASE WHEN p.estado='prestado' THEN 0 ELSE 1 END,p.prestado_en DESC LIMIT 500`,[estado]);res.json(r.rows);});
router.post('/prestamos',async(req,res)=>{const {item_id,estudiante_id,cantidad,vence_el,observacion}=req.body;const cant=Math.max(1,Number(cantidad)||1);const client=await pool.connect();try{await client.query('BEGIN');const d=await client.query(`SELECT i.stock_total-COALESCE((SELECT SUM(p.cantidad) FROM biblioteca_prestamos p WHERE p.item_id=i.id AND p.estado='prestado'),0)::int AS disponibles FROM biblioteca_items i WHERE i.id=$1 AND i.activo=true FOR UPDATE`,[item_id]);if(!d.rows.length||Number(d.rows[0].disponibles)<cant){await client.query('ROLLBACK');return res.status(409).json({error:'No hay suficientes unidades disponibles.'});}const r=await client.query(`INSERT INTO biblioteca_prestamos(item_id,estudiante_id,cantidad,vence_el,observacion,creado_por) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[item_id,estudiante_id,cant,vence_el||null,observacion||'',req.session.usuario.id]);await client.query('COMMIT');res.json(r.rows[0]);}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}});
router.put('/prestamos/:id/devolver',async(req,res)=>{const r=await pool.query(`UPDATE biblioteca_prestamos SET estado='devuelto',devuelto_en=NOW(),devuelto_por=$1 WHERE id=$2 AND estado='prestado' RETURNING *`,[req.session.usuario.id,req.params.id]);if(!r.rows.length)return res.status(404).json({error:'Préstamo activo no encontrado'});res.json(r.rows[0]);});
module.exports=router;
